#!/bin/bash
# Generate Claude Usage Report
#
# Generates a summary report of Claude Code usage and costs.
#
# Usage: ./scripts/claude/generate-report.sh [--format=md|json]

set -e

FEATURES_FILE="docs/claude/metrics/features.json"
COSTS_FILE="docs/claude/metrics/costs.json"
QUEUE_FILE="enhancements/_queue.json"

FORMAT="md"
for arg in "$@"; do
  case "$arg" in
    --format=*) FORMAT="${arg#*=}" ;;
  esac
done

# Check if metrics exist
if [ ! -f "$FEATURES_FILE" ]; then
  echo "No metrics found. Run some features first!"
  exit 0
fi

# Get statistics
TOTAL_FEATURES=$(jq 'length' "$FEATURES_FILE" 2>/dev/null || echo "0")
TOTAL_DURATION=$(jq '[.[].duration_minutes] | add // 0' "$FEATURES_FILE" 2>/dev/null || echo "0")
TOTAL_FILES_CREATED=$(jq '[.[].files_created] | add // 0' "$FEATURES_FILE" 2>/dev/null || echo "0")
TOTAL_FILES_MODIFIED=$(jq '[.[].files_modified] | add // 0' "$FEATURES_FILE" 2>/dev/null || echo "0")
TOTAL_TOKENS=$(jq '[.[].tokens_estimated] | add // 0' "$FEATURES_FILE" 2>/dev/null || echo "0")
TOTAL_COST=$(jq '.total // 0' "$COSTS_FILE" 2>/dev/null || echo "0")

# Get last 5 features
RECENT_FEATURES=$(jq -r '.[-5:] | reverse | .[] | "- \(.slug) (\(.duration_minutes)min)"' "$FEATURES_FILE" 2>/dev/null || echo "None")

# Current feature
CURRENT=""
if [ -f "$QUEUE_FILE" ]; then
  CURRENT=$(jq -r '.current_feature // "None"' "$QUEUE_FILE" 2>/dev/null || echo "None")
fi

if [ "$FORMAT" = "json" ]; then
  cat <<EOF
{
  "total_features": $TOTAL_FEATURES,
  "total_duration_minutes": $TOTAL_DURATION,
  "total_files_created": $TOTAL_FILES_CREATED,
  "total_files_modified": $TOTAL_FILES_MODIFIED,
  "total_tokens": $TOTAL_TOKENS,
  "estimated_cost_usd": $TOTAL_COST,
  "current_feature": "$CURRENT"
}
EOF
else
  cat <<EOF
# Claude Code Usage Report

Generated: $(date +%Y-%m-%d)

## Summary

| Metric | Value |
|--------|-------|
| Total Features | $TOTAL_FEATURES |
| Total Time | ${TOTAL_DURATION} minutes |
| Files Created | $TOTAL_FILES_CREATED |
| Files Modified | $TOTAL_FILES_MODIFIED |
| Tokens Used | ~$TOTAL_TOKENS |
| Estimated Cost | \$$TOTAL_COST |

## Current Feature

**$CURRENT**

## Recent Features

$RECENT_FEATURES

## Cost Breakdown

$(jq -r '.features | to_entries | .[] | "- \(.key): $\(.value.total)"' "$COSTS_FILE" 2>/dev/null || echo "No cost data")

---
*Generated by CloudVault Claude Scripts*
EOF
fi
